import sys, os

# Canonical category list: id, python/json key, PascalCase library suffix,
# public entry-point function name. Every category shares the SAME 8-feature
# shape (amount/treasury bps, recipient seen-before, prior-count,
# hourly-outflow bps, seconds-since-last, reputation, amount/avg-ratio,
# is-contract) computed identically on-chain — categories differ in what
# GuardModel was TRAINED to consider risky given those numbers, not in how
# the numbers are computed. Wiring category-specific on-chain data sources
# (real NFT floor prices, real swap slippage, etc.) is future work; today
# every category reasons over the same generic trust/pattern signals.
CATEGORIES = [
    (0, "api_payment", "ApiPayment", "proposePayment"),
    (1, "nft_purchase", "NftPurchase", "proposeNftPurchase"),
    (2, "defi_swap", "DefiSwap", "proposeSwap"),
    (3, "subscription", "Subscription", "proposeSubscription"),
    (4, "treasury_dao", "TreasuryDao", "proposeGrant"),
    (5, "social_tip", "SocialTip", "proposeTip"),
]
BY_KEY = {c[1]: c for c in CATEGORIES}

# Platform treasury: receives the 0.1% protocol fee on every executed or
# released payment of a generated vault. Hard-coded so it's visible in the
# source and can't be changed after deploy.
TREASURY = "0x3D254CE41d2462A1292aAD726A39E6845fcDe452"
PROTOCOL_FEE_BPS = 10


def bitmask(keys: list[str]) -> int:
    return sum(1 << BY_KEY[k][0] for k in keys)


def generate(keys: list[str], contract_name: str = "MultiGuardVault") -> str:
    selected = [BY_KEY[k] for k in keys]
    imports = "\n".join(f'import {{GuardModel{suf}}} from "../categories/GuardModel{suf}.sol";' for _, key, suf, _ in selected if key != "api_payment")
    if any(k == "api_payment" for _, k, _, _ in selected):
        imports = 'import {GuardModel} from "../GuardModel.sol";\n' + imports

    entry_fns = []
    for cid, _key, _suf, fn in selected:
        entry_fns.append(f"""
    function {fn}(address payable to, uint256 amount) external returns (uint8 d) {{
        d = _propose({cid}, to, amount);
    }}""")

    dispatch_cases = []
    for cid, key, suf, _ in selected:
        lib = "GuardModel" if key == "api_payment" else f"GuardModel{suf}"
        dispatch_cases.append(f"""        if (category == {cid}) {{ (d, o) = {lib}.decide(x); return (d, o); }}""")

    mask = bitmask(keys)

    body = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import {{IReputation}} from "../KeylessVault.sol";
{imports}

/// Auto-generated by generate_vault.py - categories: {", ".join(keys)}
/// (bitmask {mask}). Same hard backstops and trust model as KeylessVault,
/// dispatched across {len(selected)} category-specific trained guards.
/// Every payment that leaves the vault also sends PROTOCOL_FEE_BPS of the
/// amount to the platform TREASURY.
contract {contract_name} {{
    address public immutable owner;
    IReputation public immutable rep;
    uint8 public constant CATEGORY_MASK = {mask};
    uint256 public constant DELAY = 600;
    uint256 public constant HARD_CAP_BPS = 2000;
    address public constant TREASURY = {TREASURY};
    uint256 public constant PROTOCOL_FEE_BPS = {PROTOCOL_FEE_BPS};

    mapping(address => uint256) public paidCount;
    uint256 public totalPaid; uint256 public numPaid;
    uint256 public lastOut; uint256 public windowStart; uint256 public windowOut;

    mapping(address => bool) public allow;
    uint256 public dayStart; uint256 public dayUnknownOut; uint256 public dayCap;
    uint256 public constant UNKNOWN_DAILY_BPS = 100;
    function setAllow(address a, bool b) external {{ require(msg.sender == owner); allow[a] = b; }}
    function trusted(address a) public view returns (bool) {{ return allow[a] || rep.score(a) >= 50; }}

    struct Pending {{ address to; uint256 amount; uint64 releaseAt; bool vetoed; bool done; }}
    Pending[] public pending;

    event Executed(uint8 indexed category, address indexed to, uint256 amount, int256[3] logits);
    event Delayed(uint8 indexed category, uint256 indexed id, address indexed to, uint256 amount, int256[3] logits);
    event Rejected(uint8 indexed category, address indexed to, uint256 amount, int256[3] logits);
    event ProtocolFee(address indexed to, uint256 amount, uint256 fee);

    // owner_ is explicit because the registry factory, not the owner, sends
    // the deploy transaction.
    constructor(IReputation _rep, address owner_) payable {{ owner = owner_; rep = _rep; windowStart = block.timestamp; }}
    receive() external payable {{}}

    function features(address to, uint256 amount) public view returns (int256[8] memory x) {{
        uint256 t = address(this).balance;
        uint256 wOut = block.timestamp - windowStart > 3600 ? 0 : windowOut;
        uint256 since = lastOut == 0 ? 3600 : block.timestamp - lastOut;
        uint256 avg = numPaid == 0 ? 0 : totalPaid / numPaid;
        uint256 c = paidCount[to];
        x[0] = int256(amount * 10000 / t);
        x[1] = c > 0 ? int256(1) : int256(0);
        x[2] = int256(c > 50 ? 50 : c);
        x[3] = int256((wOut + amount) * 10000 / t);
        x[4] = int256(since > 3600 ? 3600 : since);
        x[5] = int256(uint256(rep.score(to)));
        uint256 ratio = avg == 0 ? 100 : amount * 100 / avg;
        x[6] = int256(ratio > 5000 ? 5000 : ratio);
        x[7] = to.code.length > 0 ? int256(1) : int256(0);
    }}

    function _decide(uint8 category, int256[8] memory x) internal pure returns (uint8 d, int256[3] memory o) {{
{chr(10).join(dispatch_cases)}
        revert("unknown category");
    }}
{"".join(entry_fns)}

    function _propose(uint8 category, address payable to, uint256 amount) internal returns (uint8 d) {{
        int256[3] memory o;
        (d, o) = _decide(category, features(to, amount));
        if (amount * 10000 > address(this).balance * HARD_CAP_BPS) d = 2;
        if (block.timestamp - dayStart > 86400) {{ dayStart = block.timestamp; dayUnknownOut = 0; dayCap = address(this).balance * UNKNOWN_DAILY_BPS / 10000; }}
        if (!trusted(to) && dayUnknownOut + amount > dayCap) d = 2;
        if (d == 0) {{ _pay(to, amount); emit Executed(category, to, amount, o); }}
        else if (d == 1) {{ pending.push(Pending(to, amount, uint64(block.timestamp + DELAY), false, false)); emit Delayed(category, pending.length - 1, to, amount, o); }}
        else emit Rejected(category, to, amount, o);
    }}

    function veto(uint256 id) external {{ require(msg.sender == owner); pending[id].vetoed = true; }}
    function release(uint256 id) external {{
        Pending storage p = pending[id];
        require(!p.vetoed && !p.done && block.timestamp >= p.releaseAt);
        p.done = true; _pay(payable(p.to), p.amount);
    }}

    function _pay(address payable to, uint256 amount) internal {{
        if (block.timestamp - windowStart > 3600) {{ windowStart = block.timestamp; windowOut = 0; }}
        windowOut += amount; lastOut = block.timestamp;
        if (trusted(to)) paidCount[to] += 1; else dayUnknownOut += amount;
        totalPaid += amount; numPaid += 1;
        (bool ok,) = to.call{{value: amount}}(""); require(ok);
        uint256 fee = amount * PROTOCOL_FEE_BPS / 10000;
        if (fee > 0) {{
            (ok,) = TREASURY.call{{value: fee}}(""); require(ok);
            emit ProtocolFee(to, amount, fee);
        }}
    }}
}}
"""
    return body


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("keys", nargs="*")
    ap.add_argument("--name", default="MultiGuardVault")
    ap.add_argument("--out", default="src/generated/MultiGuardVault.sol")
    args = ap.parse_args()
    keys = args.keys or ["api_payment", "nft_purchase", "defi_swap"]
    src = generate(keys, args.name)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print(f"wrote {args.out} ({args.name}) for categories: {keys} (bitmask {bitmask(keys)})")
