import json, sys, os

TEMPLATE_HEADER = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// Auto-generated by generate_solidity.py from categories/weights_{name}.json.
/// {name} category guard: 8->16->3 ReLU MLP, integer weights (Q=1e4).
library GuardModel{camel} {{
    function logits(int256[8] memory x) internal pure returns (int256[3] memory o) {{
        int256[16] memory h;
"""

TEMPLATE_FOOTER = """    }
    /// 0 = approve, 1 = delay (owner can veto), 2 = reject
    function decide(int256[8] memory x) internal pure returns (uint8 d, int256[3] memory o) {
        o = logits(x);
        d = 0;
        if (o[1] > o[d]) d = 1;
        if (o[2] > o[d]) d = 2;
    }
}
"""


def to_camel(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


def generate(name: str) -> str:
    with open(f"categories/weights_{name}.json") as f:
        w = json.load(f)
    W1, b1, W2, b2 = w["W1"], w["b1"], w["W2"], w["b2"]
    camel = to_camel(name)
    lines = [TEMPLATE_HEADER.format(name=name, camel=camel)]
    for i in range(16):
        terms = " + ".join(f"({W1[j][i]})*x[{j}]" for j in range(8))
        lines.append(f"        h[{i}] = {terms} + ({b1[i]}); if (h[{i}] < 0) h[{i}] = 0;\n")
    for k in range(3):
        terms = " + ".join(f"h[{i}]*({W2[i][k]})" for i in range(16))
        lines.append(f"        o[{k}] = {terms} + ({b2[k]});\n")
    lines.append(TEMPLATE_FOOTER)
    return "".join(lines)


if __name__ == "__main__":
    names = sys.argv[1:] or ["nft_purchase", "defi_swap", "subscription", "treasury_dao", "social_tip"]
    os.makedirs("src/categories", exist_ok=True)
    for name in names:
        sol = generate(name)
        path = f"src/categories/GuardModel{to_camel(name)}.sol"
        with open(path, "w") as f:
            f.write(sol)
        print(f"wrote {path}")
